CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  short TEXT UNIQUE NOT NULL,
  url TEXT NOT NULL,
  created TEXT NOT NULL,
  visits INTEGER NOT NULL DEFAULT 0,
  token TEXT NOT NULL
);
