CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  short TEXT UNIQUE NOT NULL,
  url TEXT NOT NULL,
  created_at TEXT NOT NULL,
  visits INTEGER NOT NULL DEFAULT 0,
  secret TEXT
);
CREATE INDEX IF NOT EXISTS idx_short ON links(short);