openapi: 3.0.0
info:
  title: URL Shortener API
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /api-v1/:
    get:
      summary: count
      responses:
        '200':
          description: number of links
    post:
      summary: create (api-v1)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        '201':
          description: created
  /api-v2/:
    get:
      summary: home / count (HTML or JSON)
      responses:
        '200': { description: OK }
    post:
      summary: create (api-v2)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                url: { type: string }
  /api-v2/{short}:
    get:
      summary: get or redirect
      parameters:
        - name: short
          in: path
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    delete:
      summary: delete
      parameters:
        - name: short
          in: path
          required: true
          schema: { type: string }
      security:
        - api_key: []
      responses:
        '200': { description: deleted }
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-API-KEY